export const SET_BREADCRUMB = 'SET_BREADCRUMB'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_OWN_PROJECTS = 'SET_OWN_PROJECTS'
export const SET_ROLE_INFO = 'SET_ROLE_INFO'

export const SET_SUGGESTION_DIALOG = 'SET_SUGGESTION_DIALOG'
export const GET_SUGGESTION = 'GET_SUGGESTION'
export const SET_APOLLO_USER = 'SET_APOLLO_USER'